export interface Product {
  slug: string;
  name: string;
  origin: string;
  region: string;
  process: string;
  variety: string;
  altitude: string;
  flavorNotes: string[];
  shortDescription: string;
  longDescription: string;
  price: number; // cents
  stripePriceId: string;
  status: "Current Harvest" | "Limited Release" | "Signature";
  available: boolean;
  image: string;
  background: string;
  body: { title: string; description: string };
  acidity: { title: string; description: string };
  aroma: { title: string; description: string };
  featured: boolean;
}

export const products: Product[] = [
  {
    slug: "geisha",
    name: "Geisha",
    origin: "Panama",
    region: "Boquete, Chiriquí",
    process: "Washed",
    variety: "Gesha",
    altitude: "1,600–1,800 m",
    flavorNotes: ["Jasmine", "Bergamot", "Peach", "Honey"],
    shortDescription: "The crown jewel of specialty coffee. Delicate, floral, and unlike anything you've tasted.",
    longDescription: "Grown in the misty highlands of Boquete, Panama, this Gesha varietal is celebrated worldwide for its unmatched complexity. Hand-picked at peak ripeness and meticulously washed, every cup opens with jasmine and bergamot, deepening into ripe peach and wildflower honey. A transcendent experience.",
    price: 2800,
    stripePriceId: "price_geisha",
    status: "Limited Release",
    available: true,
    image: "/assets/products/geisha.png",
    background: "/assets/backgrounds/geisha.jpg",
    body: { title: "Silky", description: "Light to medium body with extraordinary clarity and a clean, lingering finish." },
    acidity: { title: "Bright", description: "Vibrant citric acidity that lifts every note to the surface." },
    aroma: { title: "Floral", description: "Intense jasmine and orange blossom — unmistakable from the first pour." },
    featured: true,
  },
  {
    slug: "golden-sunset",
    name: "Golden Sunset",
    origin: "Colombia",
    region: "Huila",
    process: "Natural",
    variety: "Castillo",
    altitude: "1,700–2,000 m",
    flavorNotes: ["Cinnamon", "Dark Chocolate", "Dried Fruit", "Caramel"],
    shortDescription: "A warm, golden cup that unfolds like a sunset over the Andes.",
    longDescription: "From the sun-drenched slopes of Huila, Colombia, this natural-process Castillo carries all the warmth of its origin. Slow-dried on raised beds under Andean skies, the beans develop an extraordinary sweetness — cinnamon, dark chocolate, and dried tropical fruit layered over a caramel finish.",
    price: 1900,
    stripePriceId: "price_golden_sunset",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/golden-sunset.png",
    background: "/assets/backgrounds/golden-sunset.jpg",
    body: { title: "Full", description: "Round, rich body with velvety texture that coats the palate beautifully." },
    acidity: { title: "Mellow", description: "Soft malic acidity that complements rather than competes with the sweetness." },
    aroma: { title: "Spiced", description: "Warm cinnamon and dark chocolate open to dried fruit as it cools." },
    featured: true,
  },
  {
    slug: "bourbon-supremo",
    name: "Bourbon Supremo",
    origin: "Colombia",
    region: "Nariño",
    process: "Washed",
    variety: "Bourbon",
    altitude: "1,800–2,200 m",
    flavorNotes: ["Brown Sugar", "Red Apple", "Walnut", "Vanilla"],
    shortDescription: "A classic Bourbon at its absolute peak — balanced, sweet, and supremely satisfying.",
    longDescription: "Sourced from extreme high-altitude farms in Nariño, where cold nights slow the cherry ripening to produce remarkable sugar concentration. The Bourbon variety at this elevation delivers a complex sweetness — brown sugar and red apple up front, with walnut and vanilla on the finish.",
    price: 2100,
    stripePriceId: "price_bourbon_supremo",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/bourbon-supremo.png",
    background: "/assets/backgrounds/bourbon.jpg",
    body: { title: "Medium", description: "Well-balanced body with a smooth, clean finish." },
    acidity: { title: "Crisp", description: "Bright apple-like acidity that keeps every sip lively." },
    aroma: { title: "Sweet", description: "Brown sugar and vanilla with a warm, inviting complexity." },
    featured: true,
  },
  {
    slug: "el-origen",
    name: "El Origen",
    origin: "Colombia",
    region: "Cauca",
    process: "Washed",
    variety: "Caturra",
    altitude: "1,600–1,900 m",
    flavorNotes: ["Citrus", "Green Apple", "Milk Chocolate", "Almond"],
    shortDescription: "Where it all began. The coffee that started Chris Rosas's obsession.",
    longDescription: "El Origen is the coffee that defines Coffee Power's philosophy — traceability, quality, and story. A classic Colombian washed Caturra from Cauca with textbook brightness and a chocolatey base that makes it endlessly approachable. This is the cup that started everything.",
    price: 1700,
    stripePriceId: "price_el_origen",
    status: "Signature",
    available: true,
    image: "/assets/products/el-origen.png",
    background: "/assets/backgrounds/el-origen.png",
    body: { title: "Medium", description: "Classic Colombian body — clean, structured, and consistent." },
    acidity: { title: "Bright", description: "Citric brightness balanced by milk chocolate sweetness." },
    aroma: { title: "Clean", description: "Fresh citrus and almond with a classic Colombian character." },
    featured: true,
  },
  {
    slug: "esencia-de-victoria",
    name: "Esencia de Victoria",
    origin: "Colombia",
    region: "Huila",
    process: "Honey",
    variety: "Pink Bourbon",
    altitude: "1,750–2,000 m",
    flavorNotes: ["Rose", "Hibiscus", "Raspberry", "Brown Sugar"],
    shortDescription: "Rare Pink Bourbon processed with care. Floral, fruity, and distinctly feminine.",
    longDescription: "Pink Bourbon is one of the rarest varieties in Colombia. This honey-processed lot from Huila expresses extraordinary floral complexity — rose petals and hibiscus give way to fresh raspberry and brown sugar sweetness. An expression of the land at its most generous.",
    price: 2400,
    stripePriceId: "price_esencia_victoria",
    status: "Limited Release",
    available: true,
    image: "/assets/products/esencia-de-victoria.png",
    background: "/assets/backgrounds/esencia-victoria.jpg",
    body: { title: "Delicate", description: "Light, tea-like body with exceptional clarity." },
    acidity: { title: "Floral", description: "Soft, floral acidity that enhances the rose and fruit notes." },
    aroma: { title: "Perfumed", description: "Intensely aromatic — rose and hibiscus on the nose." },
    featured: false,
  },
  {
    slug: "costa-rica",
    name: "Costa Rica",
    origin: "Costa Rica",
    region: "Tarrazú",
    process: "Washed",
    variety: "Caturra / Catuaí",
    altitude: "1,500–1,800 m",
    flavorNotes: ["Red Berries", "Honey", "Milk Chocolate", "Peach"],
    shortDescription: "Costa Rican precision — clean, bright, and wonderfully reliable.",
    longDescription: "From the legendary Tarrazú region, this washed lot represents Costa Rican coffee at its most expressive. The high altitude and volcanic soil contribute to exceptional clarity — red berries, honey sweetness, and a milk chocolate finish that is endlessly drinkable.",
    price: 1800,
    stripePriceId: "price_costa_rica",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/costa-rica.png",
    background: "/assets/backgrounds/costa-rica.png",
    body: { title: "Medium", description: "Clean and balanced with a smooth, inviting mouthfeel." },
    acidity: { title: "Juicy", description: "Bright, berry-forward acidity with excellent structure." },
    aroma: { title: "Fruity", description: "Red berries and honey with a hint of fresh peach." },
    featured: false,
  },
  {
    slug: "hawaii-kona-elite",
    name: "Hawaii Kona Elite",
    origin: "USA",
    region: "Kona, Big Island",
    process: "Washed",
    variety: "Kona Typica",
    altitude: "600–900 m",
    flavorNotes: ["Macadamia", "Vanilla", "Milk Chocolate", "Caramel"],
    shortDescription: "The legendary Kona. Rare, smooth, and utterly indulgent.",
    longDescription: "One of the world's most coveted coffees, grown on the volcanic slopes of Mauna Loa. The mineral-rich lava soil and coastal climate produce a cup of extraordinary smoothness — macadamia richness, vanilla sweetness, and a milk chocolate finish. True island luxury.",
    price: 3200,
    stripePriceId: "price_hawaii",
    status: "Limited Release",
    available: true,
    image: "/assets/products/hawaii.png",
    background: "/assets/backgrounds/hawaii.png",
    body: { title: "Rich", description: "Full, buttery body with a silky, smooth finish." },
    acidity: { title: "Low", description: "Very gentle acidity — deeply approachable and mellow." },
    aroma: { title: "Nutty", description: "Macadamia and vanilla with warm caramel undertones." },
    featured: false,
  },
  {
    slug: "kenia-premium",
    name: "Kenia Premium",
    origin: "Kenya",
    region: "Kirinyaga",
    process: "Washed (Double Fermented)",
    variety: "SL28 / SL34",
    altitude: "1,700–2,000 m",
    flavorNotes: ["Blackcurrant", "Tomato", "Grapefruit", "Dark Berry"],
    shortDescription: "Kenya's legendary SL varietals. Bold, complex, and unmistakably African.",
    longDescription: "Kenya's SL28 and SL34 varietals are globally celebrated for their intense fruit complexity. This double-fermented lot from Kirinyaga pushes that complexity further — blackcurrant and tomato brightness give way to grapefruit and dark berry depth. Challenging, rewarding, unforgettable.",
    price: 2300,
    stripePriceId: "price_kenia",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/kenia-premium.png",
    background: "/assets/backgrounds/kenia.jpg",
    body: { title: "Full", description: "Big, complex body with a wine-like structure." },
    acidity: { title: "Bold", description: "Intense blackcurrant-like acidity — Kenya's signature." },
    aroma: { title: "Complex", description: "Dark berry and citrus peel with a savory, wine-like depth." },
    featured: false,
  },
  {
    slug: "nicaragua",
    name: "Nicaragua",
    origin: "Nicaragua",
    region: "Jinotega",
    process: "Washed",
    variety: "Pacamara",
    altitude: "1,400–1,700 m",
    flavorNotes: ["Stone Fruit", "Dark Chocolate", "Brown Sugar", "Walnut"],
    shortDescription: "Nicaraguan Pacamara — large beans, big flavors, and a generous spirit.",
    longDescription: "The Pacamara variety produces enormous beans with an equally big flavor profile. From Jinotega's shaded farms, this washed lot delivers stone fruit brightness balanced by dark chocolate depth and brown sugar sweetness — a coffee that reveals more with every cup.",
    price: 1750,
    stripePriceId: "price_nicaragua",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/nicaragua.png",
    background: "/assets/backgrounds/nicaragua.png",
    body: { title: "Full", description: "Generous, heavy body with a lasting, chocolate finish." },
    acidity: { title: "Balanced", description: "Stone fruit acidity well-balanced by deep sweetness." },
    aroma: { title: "Rich", description: "Dark chocolate and ripe stone fruit from the first breath." },
    featured: false,
  },
  {
    slug: "panama-geisha",
    name: "Panama Geisha",
    origin: "Panama",
    region: "Volcán, Chiriquí",
    process: "Natural",
    variety: "Gesha",
    altitude: "1,500–1,700 m",
    flavorNotes: ["Tropical Fruit", "Jasmine", "Strawberry", "Elderflower"],
    shortDescription: "Natural-processed Gesha from Panama's volcanic slopes. Intoxicating.",
    longDescription: "Where the washed Geisha offers clarity, this natural-processed sister shows its wilder side. Tropical fruit intensity — mango, strawberry, and passionfruit — intertwined with the variety's signature jasmine and elderflower. Grown on the slopes of Volcán Barú in the richest volcanic soils in Central America.",
    price: 3000,
    stripePriceId: "price_panama_geisha",
    status: "Limited Release",
    available: true,
    image: "/assets/products/panama.png",
    background: "/assets/backgrounds/panama.jpg",
    body: { title: "Silky", description: "Smooth, medium body with a clean, fruit-forward finish." },
    acidity: { title: "Bright", description: "Tropical fruit acidity — vibrant and juicy." },
    aroma: { title: "Exotic", description: "Jasmine and tropical fruit — intoxicating from the dry fragrance." },
    featured: false,
  },
  {
    slug: "peru",
    name: "Peru",
    origin: "Peru",
    region: "Cajamarca",
    process: "Washed",
    variety: "Caturra / Bourbon",
    altitude: "1,600–2,000 m",
    flavorNotes: ["Apple", "Citrus", "Honey", "Almond"],
    shortDescription: "Peruvian high altitude clarity. Fresh, sweet, and perfectly balanced.",
    longDescription: "From the high-altitude farms of Cajamarca in northern Peru, where Andean mists slow-ripen the cherries to extraordinary sweetness. A clean, balanced washed lot with apple brightness, citrus notes, honey sweetness, and a warm almond finish. A coffee that simply makes you happy.",
    price: 1650,
    stripePriceId: "price_peru",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/peru.png",
    background: "/assets/backgrounds/peru.png",
    body: { title: "Light-Medium", description: "Clean, bright body with excellent clarity." },
    acidity: { title: "Crisp", description: "Fresh apple-like acidity — lively and clean." },
    aroma: { title: "Sweet", description: "Honey and apple with a delicate almond warmth." },
    featured: false,
  },
  {
    slug: "puerto-rico",
    name: "Puerto Rico",
    origin: "Puerto Rico",
    region: "Yauco",
    process: "Washed",
    variety: "Bourbon",
    altitude: "600–1,000 m",
    flavorNotes: ["Caramel", "Rum", "Dark Chocolate", "Brown Sugar"],
    shortDescription: "Caribbean royalty. Puerto Rico's famous Yauco coffee, finally accessible.",
    longDescription: "Once served exclusively to the Vatican and European royalty, Puerto Rico's Yauco coffee is a Caribbean treasure. This Bourbon lot carries all the island's warmth — rich caramel, a hint of rum, dark chocolate, and brown sugar sweetness. Smooth, full, and unmistakably tropical.",
    price: 2200,
    stripePriceId: "price_puerto_rico",
    status: "Limited Release",
    available: true,
    image: "/assets/products/puerto-rico.png",
    background: "/assets/backgrounds/puerto-rico.jpg",
    body: { title: "Full", description: "Rich, velvety body with Caribbean warmth and depth." },
    acidity: { title: "Low", description: "Very smooth — more sweetness than acidity." },
    aroma: { title: "Warm", description: "Caramel, rum, and dark chocolate on the nose." },
    featured: false,
  },
  {
    slug: "brasil",
    name: "Brasil Cerrado Mineiro",
    origin: "Brazil",
    region: "Cerrado Mineiro, Minas Gerais",
    process: "Natural",
    variety: "Yellow Bourbon",
    altitude: "900–1,200 m",
    flavorNotes: ["Hazelnut", "Dark Chocolate", "Dried Fig", "Vanilla"],
    shortDescription: "Brazilian natural at its best — nutty, chocolatey, and deeply comforting.",
    longDescription: "From the vast, sun-soaked plateau of Cerrado Mineiro, where Brazil's best Yellow Bourbons grow. Natural-processed on the farm's drying patios, this lot develops extraordinary nuttiness and chocolate depth — hazelnut, dark chocolate, dried fig — anchored by a clean vanilla finish. The perfect everyday cup.",
    price: 1550,
    stripePriceId: "price_brasil",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/brasil.png",
    background: "/assets/backgrounds/brasil.jpg",
    body: { title: "Full", description: "Round, heavy body — the quintessential espresso foundation." },
    acidity: { title: "Low", description: "Gentle acidity with natural sweetness at the forefront." },
    aroma: { title: "Nutty", description: "Hazelnut and dark chocolate — cozy and familiar." },
    featured: false,
  },
  {
    slug: "caracolillo",
    name: "Caracolillo",
    origin: "Colombia",
    region: "Nariño",
    process: "Washed",
    variety: "Peaberry (Caracol)",
    altitude: "1,800–2,100 m",
    flavorNotes: ["Lemon", "Green Tea", "Floral", "Milk Chocolate"],
    shortDescription: "The rare peaberry — nature's concentrate. Intense and delicate at once.",
    longDescription: "Caracolillo — Spanish for 'small snail' — is the peaberry, a natural mutation where only one seed develops inside the cherry instead of two. These single beans are often denser, roast more evenly, and deliver more concentrated flavor. This Nariño peaberry shows lemon brightness, green tea delicacy, and milk chocolate depth.",
    price: 2000,
    stripePriceId: "price_caracolillo",
    status: "Limited Release",
    available: true,
    image: "/assets/products/caracolillo.png",
    background: "/assets/backgrounds/amucc.jpg",
    body: { title: "Medium", description: "Concentrated, clean body with excellent clarity." },
    acidity: { title: "Bright", description: "Lemon-like brightness with a green tea freshness." },
    aroma: { title: "Floral", description: "Delicate floral notes with clean citrus." },
    featured: false,
  },
  {
    slug: "amucc",
    name: "AMUCC",
    origin: "Colombia",
    region: "Cauca — Asociación de Mujeres",
    process: "Washed",
    variety: "Castillo / Colombia",
    altitude: "1,700–1,950 m",
    flavorNotes: ["Panela", "Tropical Fruit", "Red Cherry", "Brown Sugar"],
    shortDescription: "Produced by the women's cooperative of Cauca. Empowering, sweet, and complex.",
    longDescription: "AMUCC stands for Asociación de Mujeres Unidas del Cauca — a cooperative of women farmers who produce this exceptional lot. Beyond its extraordinary cup — panela sweetness, tropical fruit, and red cherry — this coffee represents a commitment to gender equality and community empowerment in Colombian coffee.",
    price: 1850,
    stripePriceId: "price_amucc",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/amucc.png",
    background: "/assets/backgrounds/amucc.jpg",
    body: { title: "Medium-Full", description: "Round, generous body with a sweet, lasting finish." },
    acidity: { title: "Juicy", description: "Tropical fruit acidity — bright and playful." },
    aroma: { title: "Sweet", description: "Panela and tropical fruit — welcoming and warm." },
    featured: false,
  },
  {
    slug: "el-bendecido",
    name: "El Bendecido",
    origin: "Colombia",
    region: "Huila",
    process: "Anaerobic Natural",
    variety: "Caturra",
    altitude: "1,650–1,900 m",
    flavorNotes: ["Passionfruit", "Wine", "Blueberry", "Dark Honey"],
    shortDescription: "The Blessed One. Anaerobic natural fermentation taken to its joyful extreme.",
    longDescription: "El Bendecido — 'The Blessed One' — earns its name. Anaerobic natural fermentation amplifies every fruit note to extraordinary intensity: passionfruit, wine-like complexity, blueberry, and dark honey. For those who want coffee to be an experience rather than just a beverage.",
    price: 2500,
    stripePriceId: "price_el_bendecido",
    status: "Limited Release",
    available: true,
    image: "/assets/products/el-bendecido.png",
    background: "/assets/backgrounds/el-bendecido.png",
    body: { title: "Full", description: "Wine-like body with extraordinary complexity." },
    acidity: { title: "Fermented", description: "Bold, wine-like acidity from anaerobic fermentation." },
    aroma: { title: "Intense", description: "Passionfruit and blueberry with fermented wine depth." },
    featured: false,
  },
  {
    slug: "serenidad",
    name: "Serenidad",
    origin: "Colombia",
    region: "Tolima",
    process: "Washed",
    variety: "Caturra",
    altitude: "1,500–1,800 m",
    flavorNotes: ["Chamomile", "Peach", "Honey", "White Grape"],
    shortDescription: "A cup for quiet mornings. Gentle, sweet, and deeply peaceful.",
    longDescription: "Serenidad — 'Serenity' — is exactly what it promises. From the tranquil valleys of Tolima, this delicate washed Caturra delivers chamomile-like gentleness, peach sweetness, honey, and white grape brightness. A coffee for slowing down, breathing deep, and being present.",
    price: 1700,
    stripePriceId: "price_serenidad",
    status: "Signature",
    available: true,
    image: "/assets/products/serenidad.png",
    background: "/assets/backgrounds/serenidad.jpg",
    body: { title: "Light", description: "Delicate, tea-like body — gentle and calming." },
    acidity: { title: "Soft", description: "Low, gentle acidity like biting into a ripe white peach." },
    aroma: { title: "Herbal", description: "Chamomile and honey — like a morning garden." },
    featured: false,
  },
  {
    slug: "relax",
    name: "Relax",
    origin: "Colombia",
    region: "Nariño",
    process: "Honey",
    variety: "Bourbon",
    altitude: "1,600–1,850 m",
    flavorNotes: ["Lavender", "Vanilla", "Coconut", "White Chocolate"],
    shortDescription: "Switch off. This coffee was made for unwinding.",
    longDescription: "Relax is Coffee Power's gentle invitation to slow down. A honey-processed Bourbon from Nariño, it develops extraordinary sweetness during the drying phase — lavender, vanilla, coconut, and white chocolate form a soft, comforting cup that asks nothing of you except to be present.",
    price: 1750,
    stripePriceId: "price_relax",
    status: "Signature",
    available: true,
    image: "/assets/products/relax.png",
    background: "/assets/backgrounds/relax.jpg",
    body: { title: "Medium", description: "Smooth, gentle body with honey-like sweetness." },
    acidity: { title: "Low", description: "Barely perceptible acidity — just sweetness and warmth." },
    aroma: { title: "Soft", description: "Lavender and vanilla — instantly relaxing." },
    featured: false,
  },
  {
    slug: "total-relax",
    name: "Total Relax",
    origin: "Colombia",
    region: "Huila",
    process: "Natural",
    variety: "Tabi",
    altitude: "1,700–2,000 m",
    flavorNotes: ["Plum", "Grape", "Milk Chocolate", "Honey"],
    shortDescription: "Full surrender. The deepest, sweetest cup in the collection.",
    longDescription: "If Relax is an exhale, Total Relax is lying down completely. This natural-processed Tabi from Huila develops over weeks on raised drying beds, building extraordinary fruit sweetness — plum, grape, milk chocolate, and honey. The Tabi variety, unique to Colombia, adds an unmistakable elegance.",
    price: 1900,
    stripePriceId: "price_total_relax",
    status: "Signature",
    available: true,
    image: "/assets/products/total-relax.png",
    background: "/assets/backgrounds/relax.jpg",
    body: { title: "Full", description: "Dense, syrupy sweetness — the definition of comfort." },
    acidity: { title: "Soft", description: "Natural fruit acids wrapped in sweetness." },
    aroma: { title: "Sweet", description: "Plum and grape with milk chocolate warmth." },
    featured: false,
  },
  {
    slug: "night-edition",
    name: "Night Edition",
    origin: "Colombia",
    region: "Antioquia",
    process: "Dark Roast / Natural",
    variety: "Caturra Blend",
    altitude: "1,400–1,700 m",
    flavorNotes: ["Dark Chocolate", "Espresso", "Tobacco", "Roasted Almond"],
    shortDescription: "When the day is done. Coffee Power's boldest, darkest cup.",
    longDescription: "Night Edition is Coffee Power's homage to the classic espresso tradition — a bold, dark-roasted natural blend from Antioquia developed specifically for late evenings and after-dinner enjoyment. Dark chocolate intensity, tobacco depth, roasted almond richness. The cup that ends the day right.",
    price: 1600,
    stripePriceId: "price_night_edition",
    status: "Signature",
    available: true,
    image: "/assets/products/night-edition.png",
    background: "/assets/backgrounds/night-edition.jpg",
    body: { title: "Full-Bold", description: "Heavy, intense body — built for espresso." },
    acidity: { title: "Low", description: "Dark roast smooths acidity to near zero." },
    aroma: { title: "Bold", description: "Dark chocolate and roasted almond — powerful and comforting." },
    featured: false,
  },
  {
    slug: "supremo",
    name: "Supremo",
    origin: "Colombia",
    region: "Multiple Regions",
    process: "Washed",
    variety: "Supremo Screen 17+",
    altitude: "1,500–2,000 m",
    flavorNotes: ["Milk Chocolate", "Caramel", "Red Fruit", "Walnut"],
    shortDescription: "Colombia's classic grade. The supreme everyday Colombian experience.",
    longDescription: "Supremo refers to Colombia's largest screen size — beans graded 17+ for exceptional density and uniform roasting. This blend of Colombia's finest washed regions delivers the quintessential Colombian cup: milk chocolate sweetness, caramel richness, red fruit brightness, and walnut warmth. Supremely drinkable, every single day.",
    price: 1500,
    stripePriceId: "price_supremo",
    status: "Current Harvest",
    available: true,
    image: "/assets/products/supremo.png",
    background: "/assets/backgrounds/supremo-pc.jpg",
    body: { title: "Medium-Full", description: "Balanced, classic Colombian body." },
    acidity: { title: "Balanced", description: "Red fruit brightness balanced by chocolate sweetness." },
    aroma: { title: "Classic", description: "Milk chocolate and caramel — quintessentially Colombian." },
    featured: false,
  },
];

export const featuredProducts = products.filter((p) => p.featured);

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export const productCategories = {
  featured: products.filter((p) => p.featured),
  limited: products.filter((p) => p.status === "Limited Release"),
  current: products.filter((p) => p.status === "Current Harvest"),
  signature: products.filter((p) => p.status === "Signature"),
};
